
' as is

@startuml
!pragma teoz true
autonumber
autoactivate on

Box "NAD Proxy" 
participant "Proxy" as prox #GreenYellow
end box

participant "Binder" as bin

Box "other Service(NAD)" 
participant "Stub" as stub #GreenYellow
end box

== startup: initialization ==
stub -> bin: register Stub
bin --> stub:
prox -> bin: create Proxy
bin --> prox:
prox -> bin: check service available
bin --> prox:

== send request ==
alt service is available
prox -> bin: send request
bin -> stub: send request
stub --> bin:
bin --> prox:
end 

== service stub is down ==
note over stub
stub is down
end note

loop #YellowGreen
prox -> bin: check service available
bin --> prox:
end loop
@enduml



' to be

@startuml
!pragma teoz true
autonumber
' autoactivate on

Box "NAD Proxy"
participant "Proxy" as prox #GreenYellow
end box

Box "Binder"
participant "Binder driver" as dri
participant "Service Manager" as man
end box 

Box "other Service(NAD)"
participant "Stub" as stub #GreenYellow
end box

== startup: initialization ==
stub -> dri: register Stub 
dri -> man: register Stub


prox -> dri: create Proxy
dri -> man: get service


prox -[#Red]> dri: register service availability 
dri -[#Red]> man: register service availability
man -[#Red]> man: store client registration

== service stub is down ==
note over stub
stub is down
end note

dri ->> man: on binder die
man -[#Red]> man: check client registration
man -[#Red]>> dri: service is unavailable
dri -[#Red]>> prox: service is unavailable

note over prox
hold request
end note

== service stub is up ==
note over stub
stub is up
end note

stub -> dri: re-register Stub
dri -> man: re-register Stub

man -[#Red]> man: check client registration
man -[#Red]>> dri: service is available
dri -[#Red]>> prox: service is available
prox -> dri: re-create proxy
dri -> man: get service

== send request ==
prox -> dri: send request
dri -> stub: send request
@enduml