"""
Django settings for client_form_service project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# APPEND_SLASH = True

SECRET_KEY = os.environ.get('DJANGO_SECRET')

# SECRET_KEY = "django-insecure-j4w$528agqdf&a6$!lsguse*p$%@&%iwdiz*qmf4aqs9hrc$$w"


# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

ALLOWED_HOSTS = ["0.0.0.0", "localhost", os.environ.get('HOST_NAME')]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework.authtoken', # thêm app authen token
    "training_engine",
    "ocr_inference",
    "license"
]

from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=6),  # Token có hiệu lực 6 giờ
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Refresh token có hiệu lực 7 ngày
}

"""
form_label.apps.FormLabelConfig: Việc này cho phép bạn sử dụng một lớp AppConfig tùy chỉnh (FormLabelConfig) trong ứng dụng. Cấu hình này có thể chứa các thiết lập đặc biệt, bao gồm các lệnh khởi tạo, signals, hoặc bất kỳ mã khởi động nào bạn muốn chạy khi ứng dụng đó được tải.
"""

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ocr_core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],  # os.path.join(BASE_DIR, 'templates') thêm vị trí template
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ocr_core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'Test_OCR',  # Tên cơ sở dữ liệu
#         'USER': 'postgres',          # Tên người dùng PostgreSQL
#         'PASSWORD': 'admin@123',      # Mật khẩu của người dùng PostgreSQL
#         'HOST': '10.0.20.105',         # Địa chỉ máy chủ PostgreSQL (localhost nếu chạy trên máy local)
#         'PORT': '5432',              # Cổng kết nối (mặc định là 5432)
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE'),
        'NAME': os.environ.get('DB_NAME'),  # Tên cơ sở dữ liệu
        'USER': os.environ.get('DB_USER'),          # Tên người dùng PostgreSQL
        'PASSWORD': os.environ.get('DB_PASSWORD'),      # Mật khẩu của người dùng PostgreSQL
        'HOST': os.environ.get('DB_HOST'),         # Địa chỉ máy chủ PostgreSQL (localhost nếu chạy trên máy local)
        'PORT': os.environ.get('DB_PORT'),              # Cổng kết nối (mặc định là 5432)
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': "ai_training_platform",  # Tên database
#         'USER': "root",       # Tên người dùng MySQL
#         'PASSWORD': "vhoang123",   # Mật khẩu MySQL
#         'HOST': "10.36.4.159",           # Hoặc địa chỉ IP của MySQL server192.168.1.104
#         'PORT': "3306",                # Cổng mặc định của MySQL
#         # 'OPTIONS': {
#         #     'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
#         # }
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# AUTHENTICATION_BACKENDS = [
#     'ocr_core.backends.CustomUserBackend',
# ]

# AUTH_USER_MODEL = 'form_label.User' #model yêu cầu phải có REQUIRE_FIELD

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'myapp/static'),  # Chỉ định thư mục tĩnh trong myapp
# ] # Nếu bạn có thư mục static ở cấp dự án

MEDIA_URL = '/storage/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'storage')