@startuml
autonumber
actor "User" as User
participant "CodeGuard extension" as CodeGuard #Green
participant "ClangTidy" as clangtidy
participant "Cpp_Check" as cppcheck
participant "Clang" as clang


User -> CodeGuard: check C++ violoation by static analysic 
CodeGuard -> CodeGuard: get C++ filename
CodeGuard -> clangtidy: run "clang-tidy $filename"
clangtidy --> CodeGuard: response clang-tidy results
CodeGuard -> CodeGuard: write results to output file
CodeGuard -> cppcheck: run "cppcheck $filename"
cppcheck --> CodeGuard: response cppcheck results
CodeGuard -> CodeGuard: write results to output file
CodeGuard -> clang: run "clang $filename"
clang --> CodeGuard: response clang results
CodeGuard -> CodeGuard: write results to output file

CodeGuard --> User: result in output file


@enduml