
@startuml
!pragma teoz true
autonumber
autoactivate on


box "BAM SoC"
participant "Service A" as sa #Green

participant "NAD Manager" as nadm #GreenYellow
participant "SOME/IP" as sip #Yellow
end box

box "NAD SoC"
participant "NAD Relay" as nadp #GreenYellow


participant "Binder" as bind #Yellow

participant "Service C" as sc #Green

end box

== send request asynchronously ==
sa ->> nadm: request 1


note over sa
there is no response to external component
end note

nadm ->> sip: request 1
sip ->> nadp: request 1
nadp ->> bind: request 1
bind ->> sc: request 1



@enduml