@startuml
!pragma teoz true
autonumber
autoactivate on
box "NAD SoC\n"

    participant "eCall app" as ecall

    participant "Binder" as bin 

   
    participant "NAD Relay" as ecall_con_nad #99FF99

  

end box

 

box "BAM SoC\n"
   participant "SomeIP" as sip 
    participant "NAD Manager" as nadm #99FF99
  

    participant "MCP Gateway" as gw
end box

box "Backend"
    participant "MQTT broker" as bro
    participant "Backend app" as backend
end box
== backend startup ==
backend ->> bro: connect()
bro -> backend: connack()

== vehicle startup ==
gw ->> bro: connect()
bro ->> gw: connack()
nadm ->> gw: connect()
gw ->> nadm: connack()

== start interface ==
backend ->> bro: subscribe()
bro ->> backend: suback()

nadm ->> gw: subcribe()
gw ->> bro: subcribe()
bro ->> gw: suback()
gw ->> nadm: suback()

== event change ==
ecall ->> bin: sendStartEcallEvent()
bin ->> ecall_con_nad: sendStartEcallEvent()
ecall_con_nad ->> sip: sendStartEcallEvent()
sip ->> nadm: sendStartEcallEvent()

nadm ->> gw: publish()
gw ->> bro: publish()
bro ->> backend: publish()

backend ->> bro: publish()
bro ->> gw: publish()
gw ->> nadm: publish()

nadm ->> sip: onSetupEcallVoice()
sip ->> ecall_con_nad: onSetupEcallVoice()
ecall_con_nad ->> bin: onSetupEcallVoice()
bin ->> ecall: onSetupEcallVoice()

@enduml