@startuml
!pragma teoz true
autonumber
autoactivate on
box "NAD SoC\n"

    participant "LPA App" as lpa
    participant "Binder" as bin 


    participant "NAD Relay" as lpa_pr #99FF99
  

end box

   

box "BAM SoC\n"
     participant "SomeIP" as sip 
    participant "Nad Manager" as nadm #99FF99
 
    participant "MCP Gateway" as gw
end box

box "Backend"
    participant "MQTT broker" as bro
    participant "Backend app" as backend
end box

== Vehicle startup ==

gw -> bro: connect()
bro -> gw: connack()

nadm -> gw: connect()
gw -> nadm: connack()

== Start interface ==
nadm -> gw: subcribe()
gw -> bro: subcribe()
bro -> gw: suback()
gw -> nadm: suback()

== Event change ==
backend -> bro: publish()
bro -> gw: publish()

gw -> nadm: publish()


nadm -> sip: triggerSubman()
sip -> lpa_pr: triggerSubman()

lpa_pr -> bin: triggerSubman()
bin -> lpa: triggerSubman()

@enduml