!pragma teoz true
autonumber
autoactivate on
box "NAD SoC\n"

    participant "Config Manager" as config

    participant "Binder IPC" as bin 
    

   
    participant "NAD Relay" as nadm_nadm #99FF99


end box

   

box "BAM SoC\n"

     participant "SomeIP IPC" as sip 
  
    participant "NAD Manager" as nadm #99FF99
   

    participant "Provisioning Service" as nadm_data

end box



    nadm -> nadm_data: subcribeSecsions()
    loop for each session
    nadm_data -> nadm: nadmvisioningData()

    nadm -> nadm: mergeData()
    end loop


    nadm ->> sip: sendNadnadmvisioningData()
    sip ->> nadm_nadm: sendNadnadmvisioningData()
    nadm_nadm ->> bin: write()
    bin ->> config: write()


